# Generated by Django 5.1.6 on 2025-02-21 08:16

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('title', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.SmallIntegerField()),
                ('source_code', models.TextField()),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 2, 21, 8, 16, 14, 240550))),
                ('is_deleted', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('problem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.problem')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('start_line_number', models.SmallIntegerField()),
                ('end_line_number', models.SmallIntegerField()),
                ('is_passed', models.BooleanField(default=False)),
                ('history_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.history')),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_code', models.TextField()),
                ('problem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.problem')),
            ],
        ),
        migrations.CreateModel(
            name='SolutionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_line_number', models.SmallIntegerField()),
                ('end_line_number', models.SmallIntegerField()),
                ('solution_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_lines', to='review.solution')),
            ],
        ),
    ]
